### ISSUE TITLE
是迪士尼数据造假了还是数据统计方式出了问题？

### ISSUE THREAD

**Issue by timmyz** [gtt116/wait4disney#2]
hi @gtt116 , 现在看热力图中的图表，从去年10月底开始到现在一直都是很清闲（淡黄色）的状态，但实际上热度并没有减，是统计上有问题吗？

**Comment by Victor2333** [comment]
There is no record on 10.16-10.22 last year.So it cause this problem.

**Comment by timmyz** [comment]
ok, i see. thanks for the information. :)

Best Regards,
Timmy Zhang
在 2018年7月19日 +0800 AM11:02，Victor2333 <notifications@github.com>，写道：

**Comment by gtt116** [comment]
数据都是客观的，统计的算法有些问题。

之前归一化的方法是：计算当日的累计等待时间（求合），并计算历史最高的当日累计
等待时间，将该值作为归一化的基础。但是因为历史上当日累计的最高值实在太高了，
导致最近的数据看上去不大真实，没有反应出真实的等待时间。同时也会带来一个问题，
如果再次出现新的历史高点，原来的数据将会全部被改写，这样数据将变的很不稳定，
也就失去了参考的意义。

所以，现在改成了计算当日的平均等待时间，这样当日数据就是稳定的，同时将页面
上说明该值的含义，比之前一串数字来的更易懂。从目前历史数据看，平均等待时间最长
也就27分钟多一些，所以热力图上的最大值先设置为30，之后如果变化更大就让前端根据
后端数据动态计算最大值。

另外要感谢 @timmyz  @Victor2333 的关注以及提出的问题。
